### ISSUE TITLE
v11 Update?

### ISSUE THREAD

**Issue by Berytak** [CeaneC/FoundryVTT-Ranger-Fog#6]
Any plans on updating the module to v11?

Seems to work but I get two warnings:

The module "ranger-fog" contains dependencies using "name" which is deprecated in favor of "id"
The module "ranger-fog" contains "dependencies" which is deprecated in favor of "relationships.requires"

**Comment by CeaneC** [comment]
I plan on it, but haven't found the time to update to V11 yet. Once I do I'll replace the deprecated fields

**Comment by coffiarts** [comment]
Here's a pull request that should fix it: https://github.com/CeaneC/FoundryVTT-Ranger-Fog/pull/7
@CeaneC - feel free to merge.
Of course, you (as the owner) will still have to register the new version under https://foundryvtt.com/admin, so that it can be detected by Foundry's inline setup.
Hope this helps.

**Comment by coffiarts** [comment]
Seems that I've overlooked that :(. I'll create another PR within a minute

**Comment by CeaneC** [comment]
PR has been merged, so the warnings should be gone now. Let me know if any problems pop up
